COMMENT ON TABLE activate_record_replace IS '激活记录表';
COMMENT ON COLUMN activate_record_replace.employee_id IS '员工Id';
COMMENT ON COLUMN activate_record_replace.datetime_time IS '时间';
COMMENT ON TABLE department_replace IS '部门表';
COMMENT ON COLUMN department_replace.department_name IS '部门名称';
COMMENT ON COLUMN department_replace.parent_id IS '上级部门编号';
COMMENT ON COLUMN department_replace.status IS '状态 0:正常 ， 1:删除';
COMMENT ON TABLE department_center_replace IS '部门表';
COMMENT ON COLUMN department_center_replace.department_id IS '部门Id';
COMMENT ON COLUMN department_center_replace.employee_id IS '员工ID';
COMMENT ON COLUMN department_center_replace.status IS '状态(0正常 1 删除)';
COMMENT ON COLUMN department_center_replace.leader IS '是否负责人(0 不是，1是)';
COMMENT ON COLUMN department_center_replace.is_main IS '是否主部门(0 不是，1是)';
COMMENT ON TABLE employee_fabulous_replace IS '点赞中间表';
COMMENT ON COLUMN employee_fabulous_replace.fabulous_id IS '点赞ID';
COMMENT ON COLUMN employee_fabulous_replace.employee_id IS '人员ID';
COMMENT ON COLUMN employee_fabulous_replace.status IS '是否点赞(0 无  1是)';
COMMENT ON TABLE employee_replace IS '员工表';
COMMENT ON COLUMN employee_replace.employee_name IS '员工名称';
COMMENT ON COLUMN employee_replace.picture IS '头像';
COMMENT ON COLUMN employee_replace.leader IS '是否是负责人 0:不是,1:是';
COMMENT ON COLUMN employee_replace.phone IS '电话';
COMMENT ON COLUMN employee_replace.mobile_phone IS '手机';
COMMENT ON COLUMN employee_replace.email IS '邮箱';
COMMENT ON COLUMN employee_replace.birth IS '生日';
COMMENT ON COLUMN employee_replace.region IS '地区';
COMMENT ON COLUMN employee_replace.microblog_background IS '同事圈图片';
COMMENT ON COLUMN employee_replace.status IS '状态 0:启用,1:禁用';
COMMENT ON COLUMN employee_replace.account IS '账户';
COMMENT ON COLUMN employee_replace.is_enable IS '是否激活(0 未激活  1 已激活)';
COMMENT ON COLUMN employee_replace.post_id IS '职位';
COMMENT ON COLUMN employee_replace.role_id IS '角色';
COMMENT ON COLUMN employee_replace.del_status IS '是否删除(0:正常1:删除)';
COMMENT ON COLUMN employee_replace.sex IS '背景图片';
COMMENT ON COLUMN employee_replace.sex IS '性别';
COMMENT ON COLUMN employee_replace.sign IS '个性签名';
COMMENT ON COLUMN employee_replace.mood IS '心情符号';
COMMENT ON COLUMN employee_replace.personnel_create_by IS '创建人';
COMMENT ON COLUMN employee_replace.datetime_create_time IS '创建时间';
COMMENT ON TABLE post_replace IS '职位表';
COMMENT ON COLUMN post_replace.name IS '职位名称';
COMMENT ON COLUMN post_replace.status IS '状态(0 正常 1 删除)';
COMMENT ON TABLE role_group_replace IS '角色模块权限表';
COMMENT ON COLUMN role_group_replace.id IS '主键ID';
COMMENT ON COLUMN role_group_replace.name IS '角色组名称';
COMMENT ON COLUMN role_group_replace.sys_group IS '系统角色组';
COMMENT ON COLUMN role_group_replace.status IS '状态 0:正常 1:删除';
COMMENT ON TABLE comment_replace IS '评论表';
COMMENT ON COLUMN comment_replace.bean IS '表';
COMMENT ON COLUMN comment_replace.relation_id IS '关联ID';
COMMENT ON COLUMN comment_replace.datetime_time IS '评论时间';
COMMENT ON COLUMN comment_replace.content IS '评论内容';
COMMENT ON COLUMN comment_replace.employee_id IS '评论者';
COMMENT ON COLUMN comment_replace.information IS '附件';
COMMENT ON COLUMN comment_replace.sign_id IS '企信ID';
COMMENT ON TABLE module_page_auth_replace IS '模块页面权限表';
COMMENT ON COLUMN module_page_auth_replace.id IS '主键ID';
COMMENT ON COLUMN module_page_auth_replace.page_id IS '页面id';
COMMENT ON COLUMN module_page_auth_replace.role_id IS '角色id';
COMMENT ON COLUMN module_page_auth_replace.del_status IS '权限码(0正常 1删除)';
COMMENT ON TABLE func_auth_replace IS '功能权限表';
COMMENT ON COLUMN func_auth_replace.id IS '主键ID';
COMMENT ON COLUMN func_auth_replace.module_id IS '模块ID';
COMMENT ON COLUMN func_auth_replace.func_name IS '功能权限名称';
COMMENT ON COLUMN func_auth_replace.auth_code IS '权限码';
COMMENT ON COLUMN func_auth_replace.use_status IS '使用状态(0使用 1未使用)';
COMMENT ON COLUMN func_auth_replace.del_status IS '权限码(0正常 1删除)';
COMMENT ON TABLE func_btn_replace IS '按钮表';
COMMENT ON COLUMN func_btn_replace.id IS '主键ID';
COMMENT ON COLUMN func_btn_replace.auth_id IS '功能权限ID';
COMMENT ON COLUMN func_btn_replace.btn_name IS '按钮名称';
COMMENT ON COLUMN func_btn_replace.del_status IS '权限码(0正常 1删除)';
COMMENT ON TABLE role_replace IS '角色表';
COMMENT ON COLUMN role_replace.role_group_id IS '角色分组id';
COMMENT ON COLUMN role_replace.name IS '角色名称';
COMMENT ON COLUMN role_replace.status IS '状态 0:正常 1:删除';
COMMENT ON COLUMN role_replace.remark IS '角色描述';
COMMENT ON TABLE operation_record_replace IS '操作记录表';
COMMENT ON COLUMN operation_record_replace.relation_id IS '关联表ID';
COMMENT ON COLUMN operation_record_replace.datetime_time IS '操作时间';
COMMENT ON COLUMN operation_record_replace.content IS '内容';
COMMENT ON COLUMN operation_record_replace.bean IS '关联表';
COMMENT ON COLUMN operation_record_replace.employee_id IS '操作人';
COMMENT ON TABLE im_circle_comment_replace IS '员工角色表';
COMMENT ON COLUMN im_circle_comment_replace.id IS '主键ID';
COMMENT ON COLUMN im_circle_comment_replace.sender_id IS '评论者的ID';
COMMENT ON COLUMN im_circle_comment_replace.content_info IS '评论的内容';
COMMENT ON COLUMN im_circle_comment_replace.circle_main_id IS '企业圈的ID';
COMMENT ON COLUMN im_circle_comment_replace.datetime_create_date IS '时间';
COMMENT ON COLUMN im_circle_comment_replace.receiver_id IS '回复者的ID';
COMMENT ON TABLE im_circle_main_replace IS '员工角色表';
COMMENT ON COLUMN im_circle_main_replace.id IS '主键ID';
COMMENT ON COLUMN im_circle_main_replace.from_id IS '员工ID，谁发表的企业圈';
COMMENT ON COLUMN im_circle_main_replace.address IS '发表的地址';
COMMENT ON COLUMN im_circle_main_replace.longitude IS '经度';
COMMENT ON COLUMN im_circle_main_replace.latitude IS '维度';
COMMENT ON COLUMN im_circle_main_replace.info IS '发表的内容';
COMMENT ON COLUMN im_circle_main_replace.datetime_create_date IS '创建时间';
COMMENT ON COLUMN im_circle_main_replace.is_delete IS '是否删除0表示未，1表示删除';
COMMENT ON TABLE im_circle_photo_replace IS '头像类';
COMMENT ON COLUMN im_circle_photo_replace.circle_main_id IS '所关联的审批id';
COMMENT ON COLUMN im_circle_photo_replace.file_url IS '审批附件的url';
COMMENT ON COLUMN im_circle_photo_replace.datetime_upload_time IS '上传时间';
COMMENT ON COLUMN im_circle_photo_replace.file_name IS '文件名称';
COMMENT ON COLUMN im_circle_photo_replace.file_size IS '文件大小';
COMMENT ON COLUMN im_circle_photo_replace.file_type IS '文件后缀';
COMMENT ON TABLE im_circle_up_replace IS '员工角色表';
COMMENT ON COLUMN im_circle_up_replace.id IS '主键ID';
COMMENT ON COLUMN im_circle_up_replace.employee_id IS '点赞人的ID';
COMMENT ON COLUMN im_circle_up_replace.circle_main_id IS '企业圈的ID';
COMMENT ON TABLE push_message_content_replace IS '推送消息ID';
COMMENT ON COLUMN push_message_content_replace.id IS '应用ID';
COMMENT ON COLUMN push_message_content_replace.sender_id IS '发送者ID';
COMMENT ON COLUMN push_message_content_replace.data_id IS '发送者ID';
COMMENT ON COLUMN push_message_content_replace.type IS '推送消息类型';
COMMENT ON COLUMN push_message_content_replace.style IS '文件库文件类型';
COMMENT ON COLUMN push_message_content_replace.push_content IS '推送内容';
COMMENT ON COLUMN push_message_content_replace.bean_name IS '模块名';
COMMENT ON COLUMN push_message_content_replace.bean_name_chinese IS '应用中文名';
COMMENT ON COLUMN push_message_content_replace.datetime_create_time IS '创建时间';
COMMENT ON TABLE push_message_field_replace IS '推送消息包含字段ID';
COMMENT ON COLUMN push_message_field_replace.push_message_id IS '推送消息ID';
COMMENT ON COLUMN push_message_field_replace.field_label IS '字段名';
COMMENT ON COLUMN push_message_field_replace.field_value IS '字段值';
COMMENT ON COLUMN push_message_field_replace.type IS '组件类型';
COMMENT ON TABLE push_relevent_info_replace IS '人员和消息关联';
COMMENT ON COLUMN push_relevent_info_replace.id IS '人员和消息的ID';
COMMENT ON COLUMN push_relevent_info_replace.sign_id IS '用户的聊天ID';
COMMENT ON COLUMN push_relevent_info_replace.push_message_id IS '推送消息的ID';
COMMENT ON COLUMN push_relevent_info_replace.datetime_create_time IS '创建时间';
COMMENT ON COLUMN push_relevent_info_replace.datetime_update_time IS '查看时间';
COMMENT ON COLUMN push_relevent_info_replace.read_status IS '查看状态(0:未查看；1:已查看)';
COMMENT ON TABLE timer_task_info_replace IS '定时任务';
COMMENT ON COLUMN timer_task_info_replace.id IS '定时任务信息表';
COMMENT ON COLUMN timer_task_info_replace.job_name IS '定时任务的名称';
COMMENT ON COLUMN timer_task_info_replace.job_group_name IS '定时任务的组名';
COMMENT ON COLUMN timer_task_info_replace.trigger_name IS '触发器名';
COMMENT ON COLUMN timer_task_info_replace.trigger_group_name IS '触发器组名';
COMMENT ON COLUMN timer_task_info_replace.cron_expression IS '定时表达式';
COMMENT ON COLUMN timer_task_info_replace.datetime_create_time IS '创建时间';
COMMENT ON COLUMN timer_task_info_replace.task_status IS '任务状态(0:有效，1：无效)';
COMMENT ON TABLE timer_task_push_info_replace IS '定时任务的推送信息';
COMMENT ON COLUMN timer_task_push_info_replace.id IS '定时任务的推送信息的ID';
COMMENT ON COLUMN timer_task_push_info_replace.company_id IS '推送的消息的公司ID';
COMMENT ON COLUMN timer_task_push_info_replace.operater_id IS '推送的消息的ID';
COMMENT ON COLUMN timer_task_push_info_replace.push_type IS '推送消息的类型';
COMMENT ON COLUMN timer_task_push_info_replace.bean_name IS '推送的模块名';
COMMENT ON COLUMN timer_task_push_info_replace.datetime_create_time IS '创建时间';
COMMENT ON COLUMN timer_task_push_info_replace.push_times IS '推送次数';
COMMENT ON COLUMN timer_task_push_info_replace.job_name IS '定时任务的名称';
COMMENT ON TABLE rule_replace IS '规则';
COMMENT ON COLUMN rule_replace.title IS '规则名称';
COMMENT ON COLUMN rule_replace.triggers IS '触发事件';
COMMENT ON COLUMN rule_replace.status IS '状态(0 正常 1禁用 2删除)';
COMMENT ON COLUMN rule_replace.high_where IS '高级条件';
COMMENT ON COLUMN rule_replace.personnel_create_by IS '创建人';
COMMENT ON COLUMN rule_replace.datetime_create_time IS '创建时间';
COMMENT ON COLUMN rule_replace.condition IS '规则条件';
COMMENT ON COLUMN rule_replace.allot IS '分配机制';
COMMENT ON COLUMN rule_replace.bean IS '模块bean';
COMMENT ON COLUMN rule_replace.allot_employee IS '选择分配人';
COMMENT ON COLUMN rule_replace.target_lable IS '目标分配人lable';
COMMENT ON COLUMN rule_replace.query_condition IS '条件';
COMMENT ON TABLE rule_detail_replace IS '规则详情';
COMMENT ON COLUMN rule_detail_replace.rule_id IS '规则ID';
COMMENT ON COLUMN rule_detail_replace.field_value IS '字段value';
COMMENT ON COLUMN rule_detail_replace.field_label IS '字段label';
COMMENT ON COLUMN rule_detail_replace.operator_value IS '类型value';
COMMENT ON COLUMN rule_detail_replace.operator_label IS '类型label';
COMMENT ON COLUMN rule_detail_replace.result_value IS '输入value';
COMMENT ON COLUMN rule_detail_replace.result_label IS '输入lable';
COMMENT ON COLUMN rule_detail_replace.show_type IS 'show_type';
COMMENT ON COLUMN rule_detail_replace.operators IS 'operators';
COMMENT ON COLUMN rule_detail_replace.entrys IS 'entrys';
COMMENT ON COLUMN rule_detail_replace.sel_list IS 'sel_list';
COMMENT ON COLUMN rule_detail_replace.sel_time IS 'sel_time';
COMMENT ON COLUMN rule_detail_replace.value_field IS 'value_field';
COMMENT ON TABLE rule_colour_replace IS '规则';
COMMENT ON COLUMN rule_colour_replace.title IS '规则名称';
COMMENT ON COLUMN rule_colour_replace.status IS '状态(0 正常 1禁用 2删除)';
COMMENT ON COLUMN rule_colour_replace.high_where IS '高级条件';
COMMENT ON COLUMN rule_colour_replace.bean IS '模块bean';
COMMENT ON COLUMN rule_colour_replace.condition IS '规则条件';
COMMENT ON COLUMN rule_colour_replace.colour IS '颜色value';
COMMENT ON COLUMN rule_colour_replace.personnel_create_by IS '创建人';
COMMENT ON COLUMN rule_colour_replace.datetime_create_time IS '创建时间';
COMMENT ON COLUMN rule_colour_replace.query_condition IS '条件';
COMMENT ON TABLE rule_colour_detail_replace IS '规则详情';
COMMENT ON COLUMN rule_colour_detail_replace.rule_colour_id IS '规则ID';
COMMENT ON COLUMN rule_colour_detail_replace.field_value IS '字段value';
COMMENT ON COLUMN rule_colour_detail_replace.field_label IS '字段label';
COMMENT ON COLUMN rule_colour_detail_replace.operator_value IS '类型value';
COMMENT ON COLUMN rule_colour_detail_replace.operator_label IS '类型label';
COMMENT ON COLUMN rule_colour_detail_replace.result_value IS '输入value';
COMMENT ON COLUMN rule_colour_detail_replace.result_label IS '输入lable';
COMMENT ON COLUMN rule_colour_detail_replace.show_type IS 'show_type';
COMMENT ON COLUMN rule_colour_detail_replace.operators IS 'operators';
COMMENT ON COLUMN rule_colour_detail_replace.entrys IS 'entrys';
COMMENT ON COLUMN rule_colour_detail_replace.sel_list IS 'sel_list';
COMMENT ON COLUMN rule_colour_detail_replace.sel_time IS 'sel_time';
COMMENT ON COLUMN rule_colour_detail_replace.value_field IS 'value_field';
COMMENT ON TABLE module_colour_center_replace IS '模块颜色中间表';
COMMENT ON COLUMN module_colour_center_replace.rule_colour_id IS '规则ID';
COMMENT ON COLUMN module_colour_center_replace.bean IS '模块bean';
COMMENT ON COLUMN module_colour_center_replace.colour IS '颜色';
COMMENT ON COLUMN module_colour_center_replace.data_id IS '数据id';
COMMENT ON TABLE application_replace IS '应用表';
COMMENT ON COLUMN application_replace.name IS '应用名称';
COMMENT ON COLUMN application_replace.company_id IS '公司ID';
COMMENT ON COLUMN application_replace.topper IS '排序';
COMMENT ON COLUMN application_replace.personnel_create_by IS '创建人';
COMMENT ON COLUMN application_replace.datetime_create_time IS '创建时间';
COMMENT ON COLUMN application_replace.personnel_modify_by IS '更新人';
COMMENT ON COLUMN application_replace.datetime_modify_time IS '更新时间';
COMMENT ON COLUMN application_replace.del_status IS '删除状态 0 正常 1 删除';
COMMENT ON TABLE application_module_replace IS '应用模块表';
COMMENT ON COLUMN application_module_replace.terminal_app IS 'APP终端是否显示';
COMMENT ON COLUMN application_module_replace.application_id IS '应用ID';
COMMENT ON COLUMN application_module_replace.chinese_name IS '模块中文名称';
COMMENT ON COLUMN application_module_replace.topper IS '排序';
COMMENT ON COLUMN application_module_replace.personnel_create_by IS '创建人';
COMMENT ON COLUMN application_module_replace.datetime_create_time IS '创建时间';
COMMENT ON COLUMN application_module_replace.personnel_modify_by IS '更新人';
COMMENT ON COLUMN application_module_replace.datetime_modify_time IS '更新时间';
COMMENT ON COLUMN application_module_replace.icon IS '图标';
COMMENT ON COLUMN application_module_replace.english_name IS '模块英文名称';
COMMENT ON COLUMN application_module_replace.del_status IS '删除状态 0 正常 1 删除';
COMMENT ON TABLE application_module_page_replace IS '模块页面表';
COMMENT ON COLUMN application_module_page_replace.module_id IS '模块ID';
COMMENT ON COLUMN application_module_page_replace.page_num IS '布局ID';
COMMENT ON COLUMN application_module_page_replace.name IS '布局名称';
COMMENT ON COLUMN application_module_page_replace.personnel_create_by IS '创建人';
COMMENT ON COLUMN application_module_page_replace.datetime_create_time IS '创建时间';
COMMENT ON COLUMN application_module_page_replace.personnel_modify_by IS '更新人';
COMMENT ON COLUMN application_module_page_replace.datetime_modify_time IS '更新时间';
COMMENT ON COLUMN application_module_page_replace.del_status IS '删除状态 0 正常 1 删除';
COMMENT ON TABLE application_module_submenu_replace IS '模块子菜单功能表';
COMMENT ON COLUMN application_module_submenu_replace.module_id IS '模块ID';
COMMENT ON COLUMN application_module_submenu_replace.name IS '菜单名称';
COMMENT ON COLUMN application_module_submenu_replace.high_where IS '高级条件';
COMMENT ON COLUMN application_module_submenu_replace.type IS '是否默认创建 0：是 1：不是（可删除）';
COMMENT ON COLUMN application_module_submenu_replace.del_status IS '删除状态 0 正常 1 删除';
COMMENT ON COLUMN application_module_submenu_replace.topper IS '排序';
COMMENT ON COLUMN application_module_submenu_replace.employee_id IS '员工ID';
COMMENT ON COLUMN application_module_submenu_replace.allot_employee IS '选择分配人';
COMMENT ON COLUMN application_module_submenu_replace.target_lable IS '目标分配人lable';
COMMENT ON COLUMN application_module_submenu_replace.query_condition IS '查询条件';
COMMENT ON COLUMN application_module_submenu_replace.personnel_create_by IS '创建人';
COMMENT ON COLUMN application_module_submenu_replace.datetime_create_time IS '创建时间';
COMMENT ON COLUMN application_module_submenu_replace.personnel_modify_by IS '更新人';
COMMENT ON COLUMN application_module_submenu_replace.datetime_modify_time IS '更新时间';
COMMENT ON TABLE submenu_rule_replace IS '子菜单规则表';
COMMENT ON COLUMN submenu_rule_replace.submenu_id IS '子菜单ID';
COMMENT ON COLUMN submenu_rule_replace.field_label IS '字段描述';
COMMENT ON COLUMN submenu_rule_replace.field_value IS '字段名称';
COMMENT ON COLUMN submenu_rule_replace.operator_label IS '操作描述';
COMMENT ON COLUMN submenu_rule_replace.operator_value IS '操作名称';
COMMENT ON COLUMN submenu_rule_replace.result_label IS '字段匹配描述';
COMMENT ON COLUMN submenu_rule_replace.result_value IS '字段匹配名称';
COMMENT ON COLUMN submenu_rule_replace.personnel_create_by IS '创建人';
COMMENT ON COLUMN submenu_rule_replace.datetime_create_time IS '创建时间';
COMMENT ON COLUMN submenu_rule_replace.personnel_modify_by IS '更新人';
COMMENT ON COLUMN submenu_rule_replace.datetime_modify_time IS '更新时间';
COMMENT ON COLUMN submenu_rule_replace.show_type IS 'show_type';
COMMENT ON COLUMN submenu_rule_replace.operators IS 'operators';
COMMENT ON COLUMN submenu_rule_replace.entrys IS 'entrys';
COMMENT ON COLUMN submenu_rule_replace.sel_list IS 'sel_list';
COMMENT ON COLUMN submenu_rule_replace.sel_time IS 'sel_time';
COMMENT ON COLUMN submenu_rule_replace.value_field IS 'value_field';
COMMENT ON TABLE role_module_replace IS '角色模块权限表';
COMMENT ON COLUMN role_module_replace.id IS '主键ID';
COMMENT ON COLUMN role_module_replace.role_id IS '角色ID';
COMMENT ON COLUMN role_module_replace.module_id IS '模块ID';
COMMENT ON COLUMN role_module_replace.data_auth IS '数据权限（0查看本人数据 1查看本部门数据 2查看公司数据）';
COMMENT ON TABLE module_func_auth_replace IS '模块功能权限表';
COMMENT ON TABLE module_func_auth_replace IS '模块对应的功能权限表';
COMMENT ON COLUMN module_func_auth_replace.id IS '主键ID';
COMMENT ON COLUMN module_func_auth_replace.role_id IS '角色id';
COMMENT ON COLUMN module_func_auth_replace.module_id IS '模块id';
COMMENT ON COLUMN module_func_auth_replace.func_id IS '功能id';
COMMENT ON COLUMN module_func_auth_replace.auth_code IS '权限码';
COMMENT ON TABLE module_share_setting_replace IS '模块共享设置表';
COMMENT ON COLUMN module_share_setting_replace.title IS '规则名称';
COMMENT ON COLUMN module_share_setting_replace.bean_name IS '模块名称';
COMMENT ON COLUMN module_share_setting_replace.employee_id IS '员工ID';
COMMENT ON COLUMN module_share_setting_replace.condition IS '规则条件 0：无规则 1：选择匹配条件';
COMMENT ON COLUMN module_share_setting_replace.high_where IS '高级条件';
COMMENT ON COLUMN module_share_setting_replace.access_permissions IS '访问权限 0：只读 1：读写 2 ：读写删';
COMMENT ON COLUMN module_share_setting_replace.allot_employee IS '选择分配人';
COMMENT ON COLUMN module_share_setting_replace.target_lable IS '目标分配人lable';
COMMENT ON COLUMN module_share_setting_replace.query_condition IS '查询条件';
COMMENT ON COLUMN module_share_setting_replace.personnel_create_by IS '创建人';
COMMENT ON COLUMN module_share_setting_replace.datetime_create_time IS '创建时间';
COMMENT ON COLUMN module_share_setting_replace.personnel_modify_by IS '更新人';
COMMENT ON COLUMN module_share_setting_replace.datetime_modify_time IS '更新时间';
COMMENT ON TABLE module_share_setting_detail_replace IS '共享设置规则详情';
COMMENT ON COLUMN module_share_setting_detail_replace.share_id IS '规则ID';
COMMENT ON COLUMN module_share_setting_detail_replace.field_value IS '字段value';
COMMENT ON COLUMN module_share_setting_detail_replace.field_label IS '字段label';
COMMENT ON COLUMN module_share_setting_detail_replace.operator_value IS '类型value';
COMMENT ON COLUMN module_share_setting_detail_replace.operator_label IS '类型label';
COMMENT ON COLUMN module_share_setting_detail_replace.result_value IS '输入value';
COMMENT ON COLUMN module_share_setting_detail_replace.result_label IS '输入lable';
COMMENT ON TABLE module_data_share_setting_replace IS '模块单条数据共享设置表';
COMMENT ON COLUMN module_data_share_setting_replace.module_id IS '模块数据Id';
COMMENT ON COLUMN module_data_share_setting_replace.bean_name IS '模块名称';
COMMENT ON COLUMN module_data_share_setting_replace.employee_id IS '员工ID';
COMMENT ON COLUMN module_data_share_setting_replace.access_permissions IS '访问权限 0：只读 1：读写 2 ：读写删';
COMMENT ON COLUMN module_data_share_setting_replace.allot_employee IS '选择分配人';
COMMENT ON COLUMN module_data_share_setting_replace.target_lable IS '目标分配人lable';
COMMENT ON COLUMN module_data_share_setting_replace.personnel_create_by IS '创建人';
COMMENT ON COLUMN module_data_share_setting_replace.datetime_create_time IS '创建时间';
COMMENT ON COLUMN module_data_share_setting_replace.personnel_modify_by IS '更新人';
COMMENT ON COLUMN module_data_share_setting_replace.datetime_modify_time IS '更新时间';
COMMENT ON TABLE application_module_used_replace IS '应用模块常使用表';
COMMENT ON COLUMN application_module_used_replace.module_id IS '模块ID';
COMMENT ON COLUMN application_module_used_replace.module_id IS '员工ID';
COMMENT ON COLUMN application_module_used_replace.chinese_name IS '模块中文名称';
COMMENT ON COLUMN application_module_used_replace.english_name IS '模块英文名称';
COMMENT ON COLUMN application_module_used_replace.icon IS '图标';
COMMENT ON COLUMN application_module_used_replace.topper IS '排序';
COMMENT ON COLUMN application_module_used_replace.datetime_create_time IS '创建时间';
COMMENT ON COLUMN application_module_used_replace.personnel_create_by IS '创建人';
COMMENT ON COLUMN application_module_used_replace.personnel_modify_by IS '更新人';
COMMENT ON COLUMN application_module_used_replace.datetime_modify_time IS '更新时间';
COMMENT ON COLUMN application_module_used_replace.del_status IS '删除状态 0 正常 1 删除';
COMMENT ON TABLE catalog_table_replace IS '文件库目录表';
COMMENT ON COLUMN catalog_table_replace.name IS '名称';
COMMENT ON COLUMN catalog_table_replace.status IS '是否禁用(0是 1 否)';
COMMENT ON TABLE catalog_replace IS '应用目录表';
COMMENT ON COLUMN catalog_replace.table_id IS '文件库目录ID';
COMMENT ON COLUMN catalog_replace.model_id IS '应用模块关联ID';
COMMENT ON COLUMN catalog_replace.sign IS '标识（0文件夹 1文件）';
COMMENT ON COLUMN catalog_replace.name IS '名称';
COMMENT ON COLUMN catalog_replace.size IS '大小';
COMMENT ON COLUMN catalog_replace.url IS '路径';
COMMENT ON COLUMN catalog_replace.siffix IS '后缀';
COMMENT ON COLUMN catalog_replace.color IS '颜色';
COMMENT ON COLUMN catalog_replace.color IS '颜色';
COMMENT ON COLUMN catalog_replace.status IS '是否删除(0正常 1 删除)';
COMMENT ON COLUMN catalog_replace.create_by IS '创建人';
COMMENT ON COLUMN catalog_replace.create_time IS '创建时间';
COMMENT ON TABLE download_record_replace IS '下载历史表';
COMMENT ON COLUMN download_record_replace.file_id IS '关联文件ID';
COMMENT ON COLUMN download_record_replace.employee_id IS '下载人ID';
COMMENT ON COLUMN download_record_replace.number IS '次数';
COMMENT ON COLUMN download_record_replace.lately_time IS '时间';
COMMENT ON TABLE fabulous_center_replace IS '点赞中间表';
COMMENT ON COLUMN fabulous_center_replace.file_id IS '关联文件ID';
COMMENT ON COLUMN fabulous_center_replace.employee_id IS '人员ID';
COMMENT ON COLUMN fabulous_center_replace.status IS '是否点赞(0 无  1是)';
COMMENT ON TABLE catalog_belong_replace IS '目录设置表';
COMMENT ON COLUMN catalog_belong_replace.file_id IS '关联文件ID';
COMMENT ON COLUMN catalog_belong_replace.type IS '类型 0共有 1 私有';
COMMENT ON TABLE catalog_manage_replace IS '目录管理员表';
COMMENT ON COLUMN catalog_manage_replace.file_id IS '关联文件ID';
COMMENT ON COLUMN catalog_manage_replace.employee_id IS '管理员';
COMMENT ON COLUMN catalog_manage_replace.sign_type IS '是否是父级管理员（0 不是 1是）';
COMMENT ON TABLE catalog_setting_replace IS '目录权限表';
COMMENT ON COLUMN catalog_setting_replace.file_id IS '关联文件ID';
COMMENT ON COLUMN catalog_setting_replace.employee_id IS '人员ID';
COMMENT ON COLUMN catalog_setting_replace.sign IS '标识是否显示 0 显示 1 不显示';
COMMENT ON COLUMN catalog_setting_replace.upload IS '下载 0 无  1 有';
COMMENT ON COLUMN catalog_setting_replace.download IS '上传 0 无  1 有';
COMMENT ON COLUMN catalog_setting_replace.preview IS '预览 0 无 1 有';
COMMENT ON TABLE catalog_version_replace IS '上传版本表';
COMMENT ON COLUMN catalog_version_replace.file_id IS '关联文件ID';
COMMENT ON COLUMN catalog_version_replace.url IS '人员ID';
COMMENT ON COLUMN catalog_version_replace.name IS '名称';
COMMENT ON COLUMN catalog_version_replace.size IS '大小';
COMMENT ON COLUMN catalog_version_replace.suffix IS '后缀';
COMMENT ON COLUMN catalog_version_replace.midf_time IS '更新时间';
COMMENT ON COLUMN catalog_version_replace.midf_by IS '更新人';
COMMENT ON TABLE catalog_share_replace IS '被分享表';
COMMENT ON COLUMN catalog_share_replace.file_id IS '关联文件ID';
COMMENT ON COLUMN catalog_share_replace.cover_id IS '关联共享ID';
COMMENT ON COLUMN catalog_share_replace.share_by IS '与我共享人ID';
COMMENT ON COLUMN catalog_share_replace.share_status IS '与我共享状态';
COMMENT ON TABLE catalog_cover_replace IS '上传版本表';
COMMENT ON COLUMN catalog_cover_replace.file_id IS '关联文件ID';
COMMENT ON COLUMN catalog_cover_replace.cover_by IS '共享人ID';
COMMENT ON COLUMN catalog_cover_replace.cover_status IS '我共享状态';
COMMENT ON TABLE approval_read_replace IS '审批是否阅读表';
COMMENT ON COLUMN approval_read_replace.process_definition_id IS '关联ID';
COMMENT ON COLUMN approval_read_replace.employee_id IS '员工ID';
COMMENT ON COLUMN approval_read_replace.status IS '是否阅读';
COMMENT ON TABLE public.attachment_replace IS '附件表';
COMMENT ON COLUMN public.attachment_replace.id IS '主键ID';
COMMENT ON COLUMN public.attachment_replace.data_id IS '数据id';
COMMENT ON COLUMN public.attachment_replace.file_name IS '附件名称';
COMMENT ON COLUMN public.attachment_replace.file_type IS '附件类型';
COMMENT ON COLUMN public.attachment_replace.file_size IS '附件大小';
COMMENT ON COLUMN public.attachment_replace.file_url IS '附件URL';
COMMENT ON COLUMN public.attachment_replace.original_file_name IS '服务器文件名称';
COMMENT ON COLUMN public.attachment_replace.serial_number IS '序列号';
COMMENT ON COLUMN public.attachment_replace.upload_by IS '附件上传者';
COMMENT ON COLUMN public.attachment_replace.upload_time IS '附件上传时间';
COMMENT ON TABLE module_seapool_setting_replace IS '模块公海池设置表';
COMMENT ON COLUMN module_seapool_setting_replace.module_id IS '模块ID';
COMMENT ON COLUMN module_seapool_setting_replace.title IS '名称';
COMMENT ON COLUMN module_seapool_setting_replace.bean_name IS '模块名称';
COMMENT ON COLUMN module_seapool_setting_replace.allot_manager IS '选择管理员';
COMMENT ON COLUMN module_seapool_setting_replace.manager_target_lable IS '目标分配人lable';
COMMENT ON COLUMN module_seapool_setting_replace.allot_employee IS '选择成员';
COMMENT ON COLUMN module_seapool_setting_replace.employee_target_lable IS '目标分配人lable';
COMMENT ON COLUMN module_seapool_setting_replace.take_limit IS '领取上限';
COMMENT ON COLUMN module_seapool_setting_replace.everyday_take_limit IS '每天领取上限';
COMMENT ON COLUMN module_seapool_setting_replace.personnel_create_by IS '创建人';
COMMENT ON COLUMN module_seapool_setting_replace.datetime_create_time IS '创建时间';
COMMENT ON COLUMN module_seapool_setting_replace.personnel_modify_by IS '更新人';
COMMENT ON COLUMN module_seapool_setting_replace.datetime_modify_time IS '更新时间';
COMMENT ON TABLE  module_seapool_setting_detail_replace IS '公海池领取详情表';
COMMENT ON COLUMN module_seapool_setting_detail_replace.seapool_id IS '公海池ID';
COMMENT ON COLUMN module_seapool_setting_detail_replace.take_by IS '领取人';
COMMENT ON COLUMN module_seapool_setting_detail_replace.take_time IS '领取时间';
COMMENT ON TABLE process_attribute_replace IS '自定义流程属性表';
COMMENT ON COLUMN process_attribute_replace.id IS '流程主键ID';
COMMENT ON COLUMN process_attribute_replace.process_instance_id IS '流程实例id'; 
COMMENT ON COLUMN process_attribute_replace.process_key IS '流程key';
COMMENT ON COLUMN process_attribute_replace.process_name IS '流程名称';
COMMENT ON COLUMN process_attribute_replace.process_type IS '流程方式（0固定流程，1自由流程）';
COMMENT ON COLUMN process_attribute_replace.module_bean IS '模块bean';
COMMENT ON COLUMN process_attribute_replace.mail_pass_way IS '邮件通过方式';
COMMENT ON COLUMN process_attribute_replace.owner_invisible IS '审批流程（0发起人可见，1发起人不可见）';
COMMENT ON COLUMN process_attribute_replace.remind_owner IS '流程提醒（每个节点审批通过都提醒发起人：0未勾选，1勾选）';
COMMENT ON COLUMN process_attribute_replace.process_operation IS '操作（0允许发起人撤回审批，1允许审批人转交审批，2允许发起人抄送审批，3允许审批人抄送审批，4允许抄送人抄送审批）';
COMMENT ON COLUMN process_attribute_replace.approver_duplicate IS '审批人去重（0不启用自动去重，1同一个审批人在流程中多次出现，自动去重，2同一个审批人在流程中连续出现，自动去重）';
COMMENT ON COLUMN process_attribute_replace.del_status IS '删除状态（0正常 1删除）';
COMMENT ON COLUMN process_attribute_replace.save_start_status IS '保存启用状态（0已部署 1已发起）';
COMMENT ON COLUMN process_attribute_replace.v_use_status IS '版本使用状态（0历史版本 1当前使用版本）';
COMMENT ON COLUMN process_attribute_replace.create_time IS '创建时间';
COMMENT ON TABLE node_attribute_replace IS '自定义节点属性表';
COMMENT ON COLUMN node_attribute_replace.id IS '节点主键ID';
COMMENT ON COLUMN node_attribute_replace.process_id IS '流程属性id';
COMMENT ON COLUMN node_attribute_replace.task_key IS '节点key';
COMMENT ON COLUMN node_attribute_replace.task_name IS '节点属性名称';
COMMENT ON COLUMN node_attribute_replace.task_type IS '节点类型';
COMMENT ON COLUMN node_attribute_replace.branch_where IS '分支条件（0任意条件均可提交、流转，1满足指定条件才可提交、流转）';
COMMENT ON COLUMN node_attribute_replace.approver_type IS '审批人类型（0单人审批，1多人审批，2部门负责人-单级，3部门负责人-多级，4指定角色，5发起人自己）';
COMMENT ON COLUMN node_attribute_replace.approver_obj IS '审批对象';
COMMENT ON COLUMN node_attribute_replace.approval_type IS '审批方式（0依次审批，1会签，2或签）';
COMMENT ON COLUMN node_attribute_replace.approval_supplement IS '待审递补（0未勾选，1勾选）';
COMMENT ON COLUMN node_attribute_replace.approval_department_single IS '单级审批部门';
COMMENT ON COLUMN node_attribute_replace.reject_type IS '驳回方式（0驳回给上一节点审批人，1驳回到发起人，2驳回到指定节点，3驳回并结束）';
COMMENT ON COLUMN node_attribute_replace.cc_to IS '抄送人';
COMMENT ON COLUMN node_attribute_replace.cc_type IS '抄送方式（0审批通过抄送，1审批驳回抄送）';
COMMENT ON TABLE node_cc_replace IS '任务节点抄送表';
COMMENT ON COLUMN node_cc_replace.id IS '主键ID';
COMMENT ON COLUMN node_cc_replace.process_definition_id IS '流程ID';
COMMENT ON COLUMN node_cc_replace.task_id IS '任务节点idy';
COMMENT ON COLUMN node_cc_replace.task_key IS '任务节点key';
COMMENT ON COLUMN node_cc_replace.cc_from IS '谁抄送';
COMMENT ON COLUMN node_cc_replace.cc_to IS '抄送给谁';
COMMENT ON COLUMN node_cc_replace.cc_time IS '抄送时间';
COMMENT ON TABLE process_whole_flow_replace IS '流程完整审批流表';
COMMENT ON COLUMN process_whole_flow_replace.id IS '主键ID';
COMMENT ON COLUMN process_whole_flow_replace.process_definition_id IS '流程ID';
COMMENT ON COLUMN process_whole_flow_replace.task_id IS '任务节点id';
COMMENT ON COLUMN process_whole_flow_replace.task_key IS '任务节点key';
COMMENT ON COLUMN process_whole_flow_replace.task_name IS '任务节点名称';
COMMENT ON COLUMN process_whole_flow_replace.task_status_id IS '任务节点状态id';
COMMENT ON COLUMN process_whole_flow_replace.task_status_name IS '任务节点状态名称';
COMMENT ON COLUMN process_whole_flow_replace.approval_employee_id IS '审批员工id';
COMMENT ON COLUMN process_whole_flow_replace.approval_message IS '节点审批备注';
COMMENT ON COLUMN process_whole_flow_replace.approval_time IS '节点审批时间';
COMMENT ON COLUMN process_whole_flow_replace.next_task_key IS '下一审批任务节点key';
COMMENT ON COLUMN process_whole_flow_replace.next_task_name IS '下一审批任务节点名称';
COMMENT ON COLUMN process_whole_flow_replace.next_approval_employee_id IS '下一审批人id';
COMMENT ON TABLE process_approval_replace IS '自定义流程属性表';
COMMENT ON COLUMN process_approval_replace.id IS '流程主键ID';
COMMENT ON COLUMN process_approval_replace.process_key IS '流程key';
COMMENT ON COLUMN process_approval_replace.process_name IS '流程名称';
COMMENT ON COLUMN process_approval_replace.process_definition_id IS '流程定义ID';
COMMENT ON COLUMN process_approval_replace.process_status IS '流程状态（0待审批 1审批中 2审批通过 3审批驳回 4已撤销 5流程结束）';
COMMENT ON COLUMN process_approval_replace.process_v IS '流程版本';
COMMENT ON COLUMN process_approval_replace.process_field_v IS '流程字段版本';
COMMENT ON COLUMN process_approval_replace.task_id IS '提交申请节点id';
COMMENT ON COLUMN process_approval_replace.module_bean IS '模块bean';
COMMENT ON COLUMN process_approval_replace.module_data_id IS '模块数据id';
COMMENT ON COLUMN process_approval_replace.approval_data_id IS '审批数据id';
COMMENT ON COLUMN process_approval_replace.begin_user_id IS '流程发起人id';
COMMENT ON COLUMN process_approval_replace.begin_user_name IS '流程发起人名称';
COMMENT ON COLUMN process_approval_replace.del_status IS '删除状态（0正常 1删除）';
COMMENT ON COLUMN process_approval_replace.create_time IS '创建时间';
COMMENT ON COLUMN application_replace.icon IS '应用图标';
insert into areplace_ACT_GE_PROPERTY values ('schema.version', '5.22.0.0', 1);
insert into areplace_ACT_GE_PROPERTY values ('schema.history', 'create(5.22.0.0)', 1);
insert into areplace_ACT_GE_PROPERTY values ('next.dbid', '1', 1);
create index areplace_ACT_IDX_EXEC_BUSKEY on areplace_ACT_RU_EXECUTION(BUSINESS_KEY_);
create index areplace_ACT_IDX_TASK_CREATE on areplace_ACT_RU_TASK(CREATE_TIME_);
create index areplace_ACT_IDX_IDENT_LNK_USER on areplace_ACT_RU_IDENTITYLINK(USER_ID_);
create index areplace_ACT_IDX_IDENT_LNK_GROUP on areplace_ACT_RU_IDENTITYLINK(GROUP_ID_);
create index areplace_ACT_IDX_EVENT_SUBSCR_CONFIG_ on areplace_ACT_RU_EVENT_SUBSCR(CONFIGURATION_);
create index areplace_ACT_IDX_VARIABLE_TASK_ID on areplace_ACT_RU_VARIABLE(TASK_ID_);
create index areplace_ACT_IDX_BYTEAR_DEPL on areplace_ACT_GE_BYTEARRAY(DEPLOYMENT_ID_);
create index areplace_ACT_IDX_EXE_PROCINST on areplace_ACT_RU_EXECUTION(PROC_INST_ID_);
create index areplace_ACT_IDX_EXE_PARENT on areplace_ACT_RU_EXECUTION(PARENT_ID_);
create index areplace_ACT_IDX_EXE_SUPER on areplace_ACT_RU_EXECUTION(SUPER_EXEC_);
create index areplace_ACT_IDX_EXE_PROCDEF on areplace_ACT_RU_EXECUTION(PROC_DEF_ID_); 
create index areplace_ACT_IDX_TSKASS_TASK on areplace_ACT_RU_IDENTITYLINK(TASK_ID_);
create index areplace_ACT_IDX_ATHRZ_PROCEDEF on areplace_ACT_RU_IDENTITYLINK(PROC_DEF_ID_);
create index areplace_ACT_IDX_IDL_PROCINST on areplace_ACT_RU_IDENTITYLINK(PROC_INST_ID_);
create index areplace_ACT_IDX_TASK_EXEC on areplace_ACT_RU_TASK(EXECUTION_ID_);
create index areplace_ACT_IDX_TASK_PROCINST on areplace_ACT_RU_TASK(PROC_INST_ID_);
create index areplace_ACT_IDX_TASK_PROCDEF on areplace_ACT_RU_TASK(PROC_DEF_ID_);
create index areplace_ACT_IDX_VAR_EXE on areplace_ACT_RU_VARIABLE(EXECUTION_ID_);
create index areplace_ACT_IDX_VAR_PROCINST on areplace_ACT_RU_VARIABLE(PROC_INST_ID_);
create index areplace_ACT_IDX_VAR_BYTEARRAY on areplace_ACT_RU_VARIABLE(BYTEARRAY_ID_);
create index areplace_ACT_IDX_JOB_EXCEPTION on areplace_ACT_RU_JOB(EXCEPTION_STACK_ID_);
create index areplace_ACT_IDX_EVENT_SUBSCR on areplace_ACT_RU_EVENT_SUBSCR(EXECUTION_ID_);
create index areplace_ACT_IDX_MODEL_SOURCE on areplace_ACT_RE_MODEL(EDITOR_SOURCE_VALUE_ID_);
create index areplace_ACT_IDX_MODEL_SOURCE_EXTRA on areplace_ACT_RE_MODEL(EDITOR_SOURCE_EXTRA_VALUE_ID_);
create index areplace_ACT_IDX_MODEL_DEPLOYMENT on areplace_ACT_RE_MODEL(DEPLOYMENT_ID_);    
create index areplace_ACT_IDX_PROCDEF_INFO_JSON on areplace_ACT_PROCDEF_INFO(INFO_JSON_ID_);
create index areplace_ACT_IDX_PROCDEF_INFO_PROC on areplace_ACT_PROCDEF_INFO(PROC_DEF_ID_);
create index areplace_ACT_IDX_HI_PRO_INST_END on areplace_ACT_HI_PROCINST(END_TIME_);
create index areplace_ACT_IDX_HI_PRO_I_BUSKEY on areplace_ACT_HI_PROCINST(BUSINESS_KEY_);
create index areplace_ACT_IDX_HI_areplace_ACT_INST_START on areplace_ACT_HI_ACTINST(START_TIME_);
create index areplace_ACT_IDX_HI_areplace_ACT_INST_END on areplace_ACT_HI_ACTINST(END_TIME_);
create index areplace_ACT_IDX_HI_DETAIL_PROC_INST on areplace_ACT_HI_DETAIL(PROC_INST_ID_);
create index areplace_ACT_IDX_HI_DETAIL_areplace_ACT_INST on areplace_ACT_HI_DETAIL(ACT_INST_ID_);
create index areplace_ACT_IDX_HI_DETAIL_TIME on areplace_ACT_HI_DETAIL(TIME_);
create index areplace_ACT_IDX_HI_DETAIL_NAME on areplace_ACT_HI_DETAIL(NAME_);
create index areplace_ACT_IDX_HI_DETAIL_TASK_ID on areplace_ACT_HI_DETAIL(TASK_ID_);
create index areplace_ACT_IDX_HI_PROCVAR_PROC_INST on areplace_ACT_HI_VARINST(PROC_INST_ID_);
create index areplace_ACT_IDX_HI_PROCVAR_NAME_TYPE on areplace_ACT_HI_VARINST(NAME_, VAR_TYPE_);
create index areplace_ACT_IDX_HI_PROCVAR_TASK_ID on areplace_ACT_HI_VARINST(TASK_ID_);
create index areplace_ACT_IDX_HI_areplace_ACT_INST_PROCINST on areplace_ACT_HI_ACTINST(PROC_INST_ID_, ACT_ID_);
create index areplace_ACT_IDX_HI_areplace_ACT_INST_EXEC on areplace_ACT_HI_ACTINST(EXECUTION_ID_, ACT_ID_);
create index areplace_ACT_IDX_HI_IDENT_LNK_USER on areplace_ACT_HI_IDENTITYLINK(USER_ID_);
create index areplace_ACT_IDX_HI_IDENT_LNK_TASK on areplace_ACT_HI_IDENTITYLINK(TASK_ID_);
create index areplace_ACT_IDX_HI_IDENT_LNK_PROCINST on areplace_ACT_HI_IDENTITYLINK(PROC_INST_ID_);
create index areplace_ACT_IDX_HI_TASK_INST_PROCINST on areplace_ACT_HI_TASKINST(PROC_INST_ID_);
COMMENT ON TABLE open_file_url_replace IS '文件库公开链接记录表';
COMMENT ON COLUMN open_file_url_replace.file_id IS '公开ID';
COMMENT ON COLUMN open_file_url_replace.visit_pwd IS '密码';
COMMENT ON COLUMN open_file_url_replace.end_time IS '有效时长';
COMMENT ON TABLE open_file_email_replace IS '文件库公开链接邮件记录表';
COMMENT ON COLUMN open_file_email_replace.file_id IS '公开ID';
COMMENT ON COLUMN open_file_email_replace.email IS '邮件';
COMMENT ON COLUMN open_file_email_replace.create_time IS '发送时间';
COMMENT ON TABLE report_replace IS '报表数据表';  
COMMENT ON COLUMN report_replace.id IS '报表数据主键ID';  
COMMENT ON COLUMN report_replace.report_name IS '报表属性名称';  
COMMENT ON COLUMN report_replace.report_label IS '报表名称';  
COMMENT ON COLUMN report_replace.data_source_name IS '数据源属性';  
COMMENT ON COLUMN report_replace.data_source_label IS '数据源名称'; 
COMMENT ON COLUMN report_replace.report_type IS '报表类型（0列表式、1汇总式、2矩阵式）'; 
COMMENT ON COLUMN report_replace.share_user IS '共享员工'; 
COMMENT ON COLUMN report_replace.share_role IS '共享角色'; 
COMMENT ON COLUMN report_replace.share_department IS '共享部门'; 
COMMENT ON COLUMN report_replace.share_company IS '共享公司'; 
COMMENT ON COLUMN report_replace.del_status IS '删除状态（0正常 1删除）';
COMMENT ON COLUMN report_replace.create_by IS '创建人';
COMMENT ON COLUMN report_replace.create_time IS '创建时间';
COMMENT ON COLUMN report_replace.modify_by IS '修改人';
COMMENT ON COLUMN report_replace.modify_time IS '修改时间';
COMMENT ON TABLE report_click_hist_replace IS '报表查看历史表';  
COMMENT ON COLUMN report_click_hist_replace.id IS '报表查看历史主键ID';  
COMMENT ON COLUMN report_click_hist_replace.report_id IS '报表id';  
COMMENT ON COLUMN report_click_hist_replace.create_by IS '查看人';
COMMENT ON COLUMN report_click_hist_replace.create_time IS '查看时间';
COMMENT ON TABLE bean_print_replace IS '打印设置表';
COMMENT ON COLUMN bean_print_replace.bean IS '模块bean';
COMMENT ON COLUMN bean_print_replace.print_type IS '类型';
COMMENT ON COLUMN bean_print_replace.template_name IS '模版名称';
COMMENT ON COLUMN bean_print_replace.url IS '地址';
COMMENT ON COLUMN bean_print_replace.create_by IS '创建人';
COMMENT ON COLUMN bean_print_replace.create_time IS '创建时间';
COMMENT ON COLUMN bean_print_replace.remark IS '描述';
COMMENT ON COLUMN bean_print_replace.del_status IS '状态 0 正常 1 删除';
COMMENT ON TABLE bean_print_url_replace IS '打印设置表';
COMMENT ON COLUMN bean_print_url_replace.bean IS '模块bean';
COMMENT ON COLUMN bean_print_url_replace.bean_id IS '打印数据ID';
COMMENT ON COLUMN bean_print_url_replace.print_url IS '打印文件路径';
COMMENT ON TABLE automation_replace IS '自动化设置表';
COMMENT ON COLUMN automation_replace.bean IS '模块bean';
COMMENT ON COLUMN automation_replace.title IS '规则名称';
COMMENT ON COLUMN automation_replace.triggers IS '触发事件';
COMMENT ON COLUMN automation_replace.remark IS '描述';
COMMENT ON COLUMN automation_replace.condition IS '规则条件';
COMMENT ON COLUMN automation_replace.query_condition IS '条件SQL';
COMMENT ON COLUMN automation_replace.query_parameter IS '整块参数';
COMMENT ON COLUMN automation_replace.del_status IS '状态 (0 正常 1 删除)';
COMMENT ON COLUMN automation_replace.create_by IS '创建人';
COMMENT ON COLUMN automation_replace.create_time IS '创建时间';
COMMENT ON TABLE automation_handle_replace IS '自动化设置更新表';
COMMENT ON COLUMN automation_handle_replace.automation_id IS '关联设置ID';
COMMENT ON COLUMN automation_handle_replace.type IS '操作类型';
COMMENT ON COLUMN automation_handle_replace.content IS '内容JSON';
COMMENT ON TABLE instrument_panel_replace IS '仪表盘设置表';
COMMENT ON COLUMN instrument_panel_replace.name IS '仪表盘名称';
COMMENT ON COLUMN instrument_panel_replace.topper IS '排序';
COMMENT ON COLUMN instrument_panel_replace.allot_employee IS '可见性';
COMMENT ON COLUMN instrument_panel_replace.target_lable IS '可见人lable';
COMMENT ON COLUMN instrument_panel_replace.del_status IS '状态 0:正常 1:删除';
COMMENT ON TABLE email_node_branch_where_replace IS '邮件节点条件表';  
COMMENT ON COLUMN email_node_branch_where_replace.id IS '邮件节点条件表主键ID';   
COMMENT ON COLUMN email_node_branch_where_replace.process_attribute_key IS '流程属性key';  
COMMENT ON COLUMN email_node_branch_where_replace.source_ref IS '源节点';  
COMMENT ON COLUMN email_node_branch_where_replace.target_ref IS '目标节点'; 
COMMENT ON COLUMN email_node_branch_where_replace.del_status IS '删除状态（0正常 1删除）';
COMMENT ON COLUMN email_node_branch_where_replace.create_by IS '创建人';
COMMENT ON COLUMN email_node_branch_where_replace.create_time IS '创建时间';
COMMENT ON TABLE email_node_branch_condistion_replace IS '邮件节点高级条件表';  
COMMENT ON COLUMN email_node_branch_condistion_replace.id IS '邮件节点高级条件表主键ID';  
COMMENT ON COLUMN email_node_branch_condistion_replace.email_where_id IS '邮件节点条件id';  
COMMENT ON COLUMN email_node_branch_condistion_replace.field_name IS '条件字段属性';  
COMMENT ON COLUMN email_node_branch_condistion_replace.field_label IS '条件字段名称';  
COMMENT ON COLUMN email_node_branch_condistion_replace.operator_name IS '操作符属性'; 
COMMENT ON COLUMN email_node_branch_condistion_replace.operator_label IS '操作符名称'; 
COMMENT ON COLUMN email_node_branch_condistion_replace.user_ids IS '用户id'; 
COMMENT ON COLUMN email_node_branch_condistion_replace.role_ids IS '角色id'; 
COMMENT ON COLUMN email_node_branch_condistion_replace.department_ids IS '部门id'; 
COMMENT ON COLUMN email_node_branch_condistion_replace.company_id IS '公司id（0未选 1全公司）'; 
COMMENT ON COLUMN email_node_branch_condistion_replace.del_status IS '删除状态（0正常 1删除）';
COMMENT ON COLUMN email_node_branch_condistion_replace.create_by IS '创建人';
COMMENT ON COLUMN email_node_branch_condistion_replace.create_time IS '创建时间';
COMMENT ON TABLE memo_replace IS '备忘录表';
COMMENT ON COLUMN memo_replace.id IS '备忘录表主键ID';
COMMENT ON COLUMN memo_replace.content IS '备忘录内容';
COMMENT ON COLUMN memo_replace.title IS '备忘录内容前25个字符';
COMMENT ON COLUMN memo_replace.pic_url IS '备忘录第一张图片地址';
COMMENT ON COLUMN memo_replace.location IS '地图定位数组信息';
COMMENT ON COLUMN memo_replace.items_arr IS '关联项目对象信息';
COMMENT ON COLUMN memo_replace.share_ids IS '共享人员编号信息';
COMMENT ON COLUMN memo_replace.remind_time IS '提醒时间';
COMMENT ON COLUMN memo_replace.remind_status IS '仅提醒自己 （0 否 、 1 是）';
COMMENT ON COLUMN memo_replace.create_time IS '创建时间';
COMMENT ON COLUMN memo_replace.create_by IS '创建人';
COMMENT ON COLUMN memo_replace.modify_time IS '更新时间';
COMMENT ON COLUMN memo_replace.modify_by IS '更改人';
COMMENT ON COLUMN memo_replace.del_status IS '是否删除（0正常 1删除 2彻底删除）';
COMMENT ON TABLE company_white_replace IS '白名单';
COMMENT ON COLUMN company_white_replace.employee_id IS '员工ID';  
COMMENT ON COLUMN company_white_replace.del_status IS '是否删除（0,正常 1 删除）';
COMMENT ON TABLE company_ip_replace IS 'ip策略';
COMMENT ON COLUMN company_ip_replace.ip IS '员工ID';  
COMMENT ON COLUMN company_ip_replace.del_status IS '是否删除（0,正常 1 删除）';
COMMENT ON COLUMN company_ip_replace.create_by IS '创建人';  
COMMENT ON COLUMN company_ip_replace.create_time IS '创建时间';
COMMENT ON TABLE  project_setting_replace IS '项目管理基本设置表';
COMMENT ON COLUMN project_setting_replace.project_id IS '项目ID';
COMMENT ON COLUMN project_setting_replace.project_status IS '项目管理状态（0进行中（启用）1归档2暂停3删除）';
COMMENT ON COLUMN project_setting_replace.project_progress_status IS '项目进度(0自动计算 1手动填写)';
COMMENT ON COLUMN project_setting_replace.project_progress_content IS '项目进度手动填写内容(正整数)';
COMMENT ON COLUMN project_setting_replace.project_remind_title IS '0系统消息提示 ';
COMMENT ON COLUMN project_setting_replace.project_remind_content IS '项目设置提醒填写内容（正整数）';
COMMENT ON COLUMN project_setting_replace.project_remind_unit IS '项目设置提醒选择单位（0分 1小时 2天）';
COMMENT ON COLUMN project_setting_replace.project_remind_type IS '项目设置提醒方式（0企信1企业微信2钉钉3邮件 ）';
COMMENT ON COLUMN project_setting_replace.project_label_ids IS '项目所拥有的标签（多个用逗号分隔）';
COMMENT ON COLUMN project_setting_replace.create_time IS '创建时间';
COMMENT ON COLUMN project_setting_replace.create_by IS '创建人';
COMMENT ON COLUMN project_setting_replace.modify_time IS '更新时间';
COMMENT ON COLUMN project_setting_replace.modify_by IS '更改人';
COMMENT ON COLUMN project_setting_replace.del_status IS '是否删除 （0 正常、 1 删除）';
COMMENT ON COLUMN project_setting_replace.project_complete_status IS '任务重新激活填写激活原因 0否 1是';
COMMENT ON COLUMN project_setting_replace.project_time_status IS '更改截止时间填写修改原因 0否 1是';
COMMENT ON COLUMN project_setting_replace.project_labels_content IS '项目设置任务排序字段josn数组字符串';
COMMENT ON TABLE  project_share_replace IS '项目分享表';
COMMENT ON COLUMN project_share_replace.project_id IS '项目ID';
COMMENT ON COLUMN project_share_replace.share_title IS '分享标题';
COMMENT ON COLUMN project_share_replace.share_content IS '分享内容';
COMMENT ON COLUMN project_share_replace.share_ids IS '共享人（逗号分隔）';
COMMENT ON COLUMN project_share_replace.share_status IS '所有成员可见（0否 1是）';
COMMENT ON COLUMN project_share_replace.submit_status IS '提交至知识库（0否 1是）';
COMMENT ON COLUMN project_share_replace.share_relevance_arr IS '关联相关（逗号分隔）';
COMMENT ON COLUMN project_share_replace.share_top_status IS '置顶状态（0否 1是）';
COMMENT ON COLUMN project_share_replace.create_time IS '创建时间';
COMMENT ON COLUMN project_share_replace.create_by IS '创建人';
COMMENT ON COLUMN project_share_replace.modify_time IS '更新时间';
COMMENT ON COLUMN project_share_replace.modify_by IS '更改人';
COMMENT ON COLUMN project_share_replace.del_status IS '是否删除 （0 正常、 1 删除）';
COMMENT ON TABLE  project_praise_history_replace IS '项目分享点赞记录表';
COMMENT ON COLUMN project_praise_history_replace.share_id IS '分享ID';
COMMENT ON COLUMN project_praise_history_replace.create_time IS '创建时间';
COMMENT ON COLUMN project_praise_history_replace.create_by IS '创建人';
COMMENT ON COLUMN project_praise_history_replace.modify_time IS '更新时间';
COMMENT ON COLUMN project_praise_history_replace.modify_by IS '更改人';
COMMENT ON COLUMN project_praise_history_replace.del_status IS '是否删除 （0 正常、 1 删除）';
COMMENT ON COLUMN project_praise_history_replace.type_status IS '点赞类型，0 分享，1任务，2子任务';
COMMENT ON TABLE  project_workbench_replace IS '工作台表';
COMMENT ON COLUMN project_workbench_replace.workbench_name IS '工作台名字';
COMMENT ON COLUMN project_workbench_replace.workbench_auth_arr IS '工作台权限数组 ';
COMMENT ON COLUMN project_workbench_replace.workbench_module_sort IS '工作台组件排序(逗号分隔)';
COMMENT ON COLUMN project_workbench_replace.workbench_sort IS '工作台排序';
COMMENT ON COLUMN project_workbench_replace.create_time IS '创建时间';
COMMENT ON COLUMN project_workbench_replace.create_by IS '创建人';
COMMENT ON COLUMN project_workbench_replace.modify_time IS '更新时间';
COMMENT ON COLUMN project_workbench_replace.modify_by IS '更改人';
COMMENT ON COLUMN project_workbench_replace.del_status IS '是否删除 （0 正常、 1 删除）';
COMMENT ON TABLE  project_task_auth_replace IS '任务权限表';
COMMENT ON COLUMN project_task_auth_replace.project_id IS '项目ID';
COMMENT ON COLUMN project_task_auth_replace.role_type IS '角色类型（0、1、2）';
COMMENT ON COLUMN project_task_auth_replace.role_type_describe IS '角色描述（创建人、执行人、协作人） ';
COMMENT ON COLUMN project_task_auth_replace.auth_1 IS '权限1（0否 1是）';
COMMENT ON COLUMN project_task_auth_replace.auth_2 IS '权限2（0否 1是）';
COMMENT ON COLUMN project_task_auth_replace.auth_3 IS '权限3（0否 1是）';
COMMENT ON COLUMN project_task_auth_replace.auth_4 IS '权限4（0否 1是）';
COMMENT ON COLUMN project_task_auth_replace.auth_5 IS '权限5（0否 1是）';
COMMENT ON COLUMN project_task_auth_replace.auth_6 IS '权限6（0否 1是）';
COMMENT ON COLUMN project_task_auth_replace.auth_7 IS '权限7（0否 1是）';
COMMENT ON COLUMN project_task_auth_replace.auth_8 IS '权限8（0否 1是）';
COMMENT ON COLUMN project_task_auth_replace.auth_9 IS '权限9（0否 1是）';
COMMENT ON COLUMN project_task_auth_replace.auth_10 IS '权限10（0否 1是）';
COMMENT ON COLUMN project_task_auth_replace.auth_11 IS '权限11（0否 1是）';
COMMENT ON COLUMN project_task_auth_replace.auth_12 IS '权限12（0否 1是）';
COMMENT ON COLUMN project_task_auth_replace.auth_13 IS '权限13（0否 1是）';
COMMENT ON COLUMN project_task_auth_replace.create_time IS '创建时间';
COMMENT ON COLUMN project_task_auth_replace.create_by IS '创建人';
COMMENT ON COLUMN project_task_auth_replace.modify_time IS '更新时间';
COMMENT ON COLUMN project_task_auth_replace.modify_by IS '更改人';
COMMENT ON COLUMN project_task_auth_replace.del_status IS '是否删除 （0 正常、 1 删除）';
COMMENT ON TABLE  project_replace IS '项目信息表';
COMMENT ON COLUMN project_replace.name IS '项目名字';
COMMENT ON COLUMN project_replace.note IS '项目描述 ';
COMMENT ON COLUMN project_replace.visual_range_status IS '可见范围（0不公开 1公开）';
COMMENT ON COLUMN project_replace.leader IS '项目负责人';
COMMENT ON COLUMN project_replace.pic_url IS '项目背景图';
COMMENT ON COLUMN project_replace.start_time IS '项目截止时间';
COMMENT ON COLUMN project_replace.end_time IS '项目截止时间';
COMMENT ON COLUMN project_replace.temp_id IS '项目使用的模板表记录ID';
COMMENT ON COLUMN project_replace.temp_status IS '是否为模板（0否 1是）';
COMMENT ON COLUMN project_replace.temp_type IS '模板类型';
COMMENT ON COLUMN project_replace.sort IS '内部排序';
COMMENT ON COLUMN project_replace.star_level IS '星标等级';
COMMENT ON COLUMN project_replace.star_time IS '星标更新时间';
COMMENT ON COLUMN project_replace.create_time IS '创建时间';
COMMENT ON COLUMN project_replace.create_by IS '创建人';
COMMENT ON COLUMN project_replace.modify_time IS '更新时间';
COMMENT ON COLUMN project_replace.modify_by IS '更改人';
COMMENT ON COLUMN project_replace.del_status IS '是否删除 （0 正常、 1 删除）';
COMMENT ON TABLE  project_main_node_replace IS '项目主流程表';
COMMENT ON COLUMN project_main_node_replace.name IS '主流程名称';
COMMENT ON COLUMN project_main_node_replace.temp_id IS '模板记录ID';
COMMENT ON COLUMN project_main_node_replace.temp_status IS '是否为模板（0否 1是）';
COMMENT ON COLUMN project_main_node_replace.project_id IS '项目id';
COMMENT ON COLUMN project_main_node_replace.sort IS '主流程排序';
COMMENT ON COLUMN project_main_node_replace.create_time IS '创建时间';
COMMENT ON COLUMN project_main_node_replace.create_by IS '创建人';
COMMENT ON COLUMN project_main_node_replace.modify_time IS '更新时间';
COMMENT ON COLUMN project_main_node_replace.modify_by IS '更改人';
COMMENT ON COLUMN project_main_node_replace.del_status IS '是否删除 （0 正常、 1 删除）';
COMMENT ON TABLE  project_sub_node_replace IS '项目子流程表';
COMMENT ON COLUMN project_sub_node_replace.name IS '子流程名称';
COMMENT ON COLUMN project_sub_node_replace.main_id IS '主流程id';
COMMENT ON COLUMN project_sub_node_replace.sort IS '子流程排序';
COMMENT ON COLUMN project_sub_node_replace.create_time IS '创建时间';
COMMENT ON COLUMN project_sub_node_replace.create_by IS '创建人';
COMMENT ON COLUMN project_sub_node_replace.modify_time IS '更新时间';
COMMENT ON COLUMN project_sub_node_replace.modify_by IS '更改人';
COMMENT ON COLUMN project_sub_node_replace.del_status IS '是否删除 （0 正常、 1 删除）';
COMMENT ON TABLE  project_task_replace IS '项目任务表';
COMMENT ON COLUMN project_task_replace.name IS '任务名称';
COMMENT ON COLUMN project_task_replace.label_id IS '标签id';
COMMENT ON COLUMN project_task_replace.description IS '任务描述';
COMMENT ON COLUMN project_task_replace.executor_id IS '执行人id';
COMMENT ON COLUMN project_task_replace.end_time IS '截止时间';
COMMENT ON COLUMN project_task_replace.finished_time IS '完成时间';
COMMENT ON COLUMN project_task_replace.accessory IS '附件地址';
COMMENT ON COLUMN project_task_replace.check_status IS '检验状态 0否 1是';
COMMENT ON COLUMN project_task_replace.join_status IS '仅参与者可见 0否	 1是';
COMMENT ON COLUMN project_task_replace.associates_status IS '仅协作人可见 0否 1是';
COMMENT ON COLUMN project_task_replace.relation_id IS '关联ID';
COMMENT ON COLUMN project_task_replace.module_id IS '模块ID';
COMMENT ON COLUMN project_task_replace.module_name IS '模块名字';
COMMENT ON COLUMN project_task_replace.bean_name IS '模块bean名字';
COMMENT ON COLUMN project_task_replace.sub_id IS '子流程ID';
COMMENT ON COLUMN project_task_replace.sort IS '任务排序';
COMMENT ON COLUMN project_task_replace.create_time IS '创建时间';
COMMENT ON COLUMN project_task_replace.create_by IS '创建人';
COMMENT ON COLUMN project_task_replace.modify_time IS '更新时间';
COMMENT ON COLUMN project_task_replace.modify_by IS '更改人';
COMMENT ON COLUMN project_task_replace.del_status IS '是否删除 （0 正常、 1 删除）';
COMMENT ON COLUMN project_task_replace.task_status IS '任务状态（0未完成、1 已完成、2待检验、3检验通过';
COMMENT ON COLUMN project_task_replace.complete_status IS '是否完成 0否 1是';
COMMENT ON COLUMN project_task_replace.complete_number IS '激活次数 0';
COMMENT ON COLUMN project_task_replace.passed_status IS '通过状态 0否 1是';
COMMENT ON COLUMN project_task_replace.task_name IS '项目任务名称';
COMMENT ON COLUMN project_task_replace.project_id IS '项目id';
COMMENT ON COLUMN project_task_replace.quote_status IS '是否为引用数据 0否，1是';
COMMENT ON TABLE  project_sub_task_replace IS '项目子任务表';
COMMENT ON COLUMN project_sub_task_replace.name IS '子任务名称';
COMMENT ON COLUMN project_sub_task_replace.end_time IS '截止时间';
COMMENT ON COLUMN project_sub_task_replace.executor_id IS '执行人id';
COMMENT ON COLUMN project_sub_task_replace.task_id IS '主任务ID';
COMMENT ON COLUMN project_sub_task_replace.relation_id IS '关联ID';
COMMENT ON COLUMN project_sub_task_replace.module_id IS '模块ID';
COMMENT ON COLUMN project_sub_task_replace.module_name IS '模块名字';
COMMENT ON COLUMN project_sub_task_replace.bean_name IS '模块bean名字';
COMMENT ON COLUMN project_sub_task_replace.sort IS '内部排序';
COMMENT ON COLUMN project_sub_task_replace.create_time IS '创建时间';
COMMENT ON COLUMN project_sub_task_replace.create_by IS '创建人';
COMMENT ON COLUMN project_sub_task_replace.modify_time IS '更新时间';
COMMENT ON COLUMN project_sub_task_replace.modify_by IS '更改人';
COMMENT ON COLUMN project_sub_task_replace.del_status IS '是否删除 （0 正常、 1 删除）';
COMMENT ON COLUMN project_sub_task_replace.check_status IS '检验状态 0否 1是';
COMMENT ON COLUMN project_sub_task_replace.check_member IS '检验人';
COMMENT ON COLUMN project_sub_task_replace.associates_status IS '仅协作人可见 0否 1是';
COMMENT ON COLUMN project_sub_task_replace.complete_status IS '是否完成 0否 1是';
COMMENT ON COLUMN project_sub_task_replace.complete_number IS '激活次数 0';
COMMENT ON COLUMN project_sub_task_replace.task_type IS '子任务信息 0，任务关联信息 1，子任务关联信息 2';
COMMENT ON COLUMN project_sub_task_replace.join_status IS '仅参与者可见 0否	 1是';
COMMENT ON COLUMN project_sub_task_replace.passed_status IS '通过状态 0否 1是';
COMMENT ON COLUMN project_sub_task_replace.project_id IS '项目id';
COMMENT ON TABLE  project_task_remind_replace IS '项目任务提醒设置表';
COMMENT ON COLUMN project_task_remind_replace.remind_type IS '提醒类型';
COMMENT ON COLUMN project_task_remind_replace.remind_time IS '提醒时间';
COMMENT ON COLUMN project_task_remind_replace.remind_content IS '提醒内容';
COMMENT ON COLUMN project_task_remind_replace.remind_unit IS '提醒单位 0分 1小时 2天';
COMMENT ON COLUMN project_task_remind_replace.reminder IS '提醒人 逗号分隔';
COMMENT ON COLUMN project_task_remind_replace.remind_way IS '提醒方式 0企信 1微信 2钉钉 3邮件';
COMMENT ON COLUMN project_task_remind_replace.create_time IS '创建时间';
COMMENT ON COLUMN project_task_remind_replace.create_by IS '创建人';
COMMENT ON COLUMN project_task_remind_replace.modify_time IS '更新时间';
COMMENT ON COLUMN project_task_remind_replace.modify_by IS '更改人';
COMMENT ON COLUMN project_task_remind_replace.del_status IS '是否删除 （0 正常、 1 删除）';
COMMENT ON TABLE  project_member_replace IS '项目子任务表';
COMMENT ON COLUMN project_member_replace.project_id IS '项目id';
COMMENT ON COLUMN project_member_replace.employee_id IS '员工ID';
COMMENT ON COLUMN project_member_replace.project_role IS '项目角色 0负责人 1执行人 2协作人 3访客 4外部人员';
COMMENT ON COLUMN project_member_replace.project_task_role IS '项目任务角色 0负责人 1执行人 2协作人';
COMMENT ON COLUMN project_member_replace.active_status IS '激活状态';
COMMENT ON COLUMN project_member_replace.external_member IS '外部成员对象（预留）';
COMMENT ON COLUMN project_member_replace.create_time IS '创建时间';
COMMENT ON COLUMN project_member_replace.create_by IS '创建人';
COMMENT ON COLUMN project_member_replace.modify_time IS '更新时间';
COMMENT ON COLUMN project_member_replace.modify_by IS '更改人';
COMMENT ON COLUMN project_member_replace.del_status IS '是否删除 （0 正常、 1 删除）';
COMMENT ON COLUMN project_member_replace.type_status IS '0 项目人员，1任务人员，2子任务人员';
COMMENT ON COLUMN project_member_replace.task_id IS '项目任务id';
COMMENT ON COLUMN project_member_replace.project_task_status IS '项目任务协作人状态 0 不可以删除的协作人，1为可以删除的协作人';
COMMENT ON COLUMN project_member_replace.father_id IS '当前如果是子任务人员，就存主任务id，方便查找与删除';
COMMENT ON TABLE project_library_replace IS '协作文库表';
COMMENT ON COLUMN project_library_replace.project_type IS ' 0 项目 1 分组 2 任务 3 文件 ';
COMMENT ON COLUMN project_library_replace.data_id IS '数据ID';
COMMENT ON COLUMN project_library_replace.file_name IS '名称';
COMMENT ON COLUMN project_library_replace.size IS '大小';
COMMENT ON COLUMN project_library_replace.url IS '路径';
COMMENT ON COLUMN project_library_replace.parent_id IS '父级ID';
COMMENT ON COLUMN project_library_replace.suffix IS '后缀';
COMMENT ON COLUMN project_library_replace.color IS '颜色';
COMMENT ON COLUMN project_library_replace.del_status IS '是否删除(0正常 1 删除)';
COMMENT ON COLUMN project_library_replace.create_by IS '创建人';
COMMENT ON COLUMN project_library_replace.create_time IS '创建时间';
COMMENT ON COLUMN project_library_replace.type IS '0 文档 1 图片 2 音频 3 视频';
COMMENT ON COLUMN project_library_replace.sort IS '排序';
COMMENT ON TABLE auto_sequence_number_replace IS '自动增长序列号表(自定义设置自动编号用)';
COMMENT ON COLUMN auto_sequence_number_replace.module_id IS '模块id';
COMMENT ON COLUMN auto_sequence_number_replace.bean IS '模块名称';
COMMENT ON COLUMN auto_sequence_number_replace.field_name IS '字段名称';
COMMENT ON COLUMN auto_sequence_number_replace.auto_number IS '自动增长序列号';
COMMENT ON TABLE redis_cache_keys_replace IS '缓存持久化表';
COMMENT ON COLUMN redis_cache_keys_replace.cache_type IS '类型';
COMMENT ON COLUMN redis_cache_keys_replace.cache_key IS '键';
COMMENT ON COLUMN redis_cache_keys_replace.cache_value IS '值';
COMMENT ON COLUMN redis_cache_keys_replace.create_time IS '缓存时间';
