alter table areplace_ACT_GE_BYTEARRAY add constraint areplace_ACT_FK_BYTEARR_DEPL foreign key (DEPLOYMENT_ID_)  references areplace_ACT_RE_DEPLOYMENT (ID_);
alter table areplace_ACT_RE_PROCDEF add constraint areplace_ACT_UNIQ_PROCDEF unique (KEY_,VERSION_, TENANT_ID_,ID_); 
alter table areplace_ACT_RU_EXECUTION add constraint areplace_ACT_FK_EXE_PROCINST  foreign key (PROC_INST_ID_)  references areplace_ACT_RU_EXECUTION (ID_);
alter table areplace_ACT_RU_EXECUTION add constraint areplace_ACT_FK_EXE_PARENT foreign key (PARENT_ID_)  references areplace_ACT_RU_EXECUTION (ID_); 
alter table areplace_ACT_RU_EXECUTION add constraint areplace_ACT_FK_EXE_SUPER foreign key (SUPER_EXEC_)  references areplace_ACT_RU_EXECUTION (ID_);
alter table areplace_ACT_RU_EXECUTION add constraint areplace_ACT_FK_EXE_PROCDEF  foreign key (PROC_DEF_ID_)  references areplace_ACT_RE_PROCDEF (ID_);    
alter table areplace_ACT_RU_IDENTITYLINK add constraint areplace_ACT_FK_TSKASS_TASK foreign key (TASK_ID_)  references areplace_ACT_RU_TASK (ID_); 
alter table areplace_ACT_RU_IDENTITYLINK add constraint areplace_ACT_FK_ATHRZ_PROCEDEF foreign key (PROC_DEF_ID_)  references areplace_ACT_RE_PROCDEF (ID_); 
alter table areplace_ACT_RU_IDENTITYLINK add constraint areplace_ACT_FK_IDL_PROCINST foreign key (PROC_INST_ID_)  references areplace_ACT_RU_EXECUTION (ID_);     
alter table areplace_ACT_RU_TASK add constraint areplace_ACT_FK_TASK_EXE foreign key (EXECUTION_ID_) references areplace_ACT_RU_EXECUTION (ID_); 
alter table areplace_ACT_RU_TASK add constraint areplace_ACT_FK_TASK_PROCINST foreign key (PROC_INST_ID_) references areplace_ACT_RU_EXECUTION (ID_); 
alter table areplace_ACT_RU_TASK add constraint areplace_ACT_FK_TASK_PROCDEF foreign key (PROC_DEF_ID_) references areplace_ACT_RE_PROCDEF (ID_);
alter table areplace_ACT_RU_VARIABLE  add constraint areplace_ACT_FK_VAR_EXE foreign key (EXECUTION_ID_)  references areplace_ACT_RU_EXECUTION (ID_);
alter table areplace_ACT_RU_VARIABLE add constraint areplace_ACT_FK_VAR_PROCINST foreign key (PROC_INST_ID_) references areplace_ACT_RU_EXECUTION(ID_);
alter table areplace_ACT_RU_VARIABLE  add constraint areplace_ACT_FK_VAR_BYTEARRAY  foreign key (BYTEARRAY_ID_)  references areplace_ACT_GE_BYTEARRAY (ID_);
alter table areplace_ACT_RU_JOB  add constraint areplace_ACT_FK_JOB_EXCEPTION foreign key (EXCEPTION_STACK_ID_)  references areplace_ACT_GE_BYTEARRAY (ID_);
alter table areplace_ACT_RU_EVENT_SUBSCR add constraint areplace_ACT_FK_EVENT_EXEC foreign key (EXECUTION_ID_) references areplace_ACT_RU_EXECUTION(ID_);
alter table areplace_ACT_RE_MODEL  add constraint areplace_ACT_FK_MODEL_SOURCE  foreign key (EDITOR_SOURCE_VALUE_ID_)  references areplace_ACT_GE_BYTEARRAY (ID_);
alter table areplace_ACT_RE_MODEL  add constraint areplace_ACT_FK_MODEL_SOURCE_EXTRA  foreign key (EDITOR_SOURCE_EXTRA_VALUE_ID_)  references areplace_ACT_GE_BYTEARRAY (ID_); 
alter table areplace_ACT_RE_MODEL  add constraint areplace_ACT_FK_MODEL_DEPLOYMENT  foreign key (DEPLOYMENT_ID_)  references areplace_ACT_RE_DEPLOYMENT (ID_);        
alter table areplace_ACT_PROCDEF_INFO  add constraint areplace_ACT_FK_INFO_JSON_BA  foreign key (INFO_JSON_ID_)  references areplace_ACT_GE_BYTEARRAY (ID_);
alter table areplace_ACT_PROCDEF_INFO  add constraint areplace_ACT_FK_INFO_PROCDEF  foreign key (PROC_DEF_ID_)  references areplace_ACT_RE_PROCDEF (ID_); 
alter table areplace_ACT_PROCDEF_INFO add constraint areplace_ACT_UNIQ_INFO_PROCDEF unique (PROC_DEF_ID_,ID_);
insert into areplace_ACT_GE_PROPERTY values ('schema.version', '5.22.0.0', 1);
insert into areplace_ACT_GE_PROPERTY values ('schema.history', 'create(5.22.0.0)', 1);
insert into areplace_ACT_GE_PROPERTY values ('next.dbid', '1', 1);