COMMENT ON TABLE mail_account_replace IS '邮件账户表';
COMMENT ON COLUMN mail_account_replace.id IS '主键ID';
COMMENT ON COLUMN mail_account_replace.account IS '邮件账号';
COMMENT ON COLUMN mail_account_replace.employee_id IS '员工ID';
COMMENT ON COLUMN mail_account_replace.password IS '邮件密码';
COMMENT ON COLUMN mail_account_replace.nickname IS '邮件昵称';
COMMENT ON COLUMN mail_account_replace.create_time IS '创建时间';
COMMENT ON COLUMN mail_account_replace.receive_server_type IS '接收服务器类型';
COMMENT ON COLUMN mail_account_replace.receive_server IS '收件服务器';
COMMENT ON COLUMN mail_account_replace.receive_server_secure IS '收件服务器传输方式';
COMMENT ON COLUMN mail_account_replace.receive_server_port IS '收件服务器端口';
COMMENT ON COLUMN mail_account_replace.receive_server IS '发件服务器';
COMMENT ON COLUMN mail_account_replace.receive_server_secure IS '发件服务器传输方式';
COMMENT ON COLUMN mail_account_replace.receive_server_port IS '发件服务器端口';
COMMENT ON COLUMN mail_account_replace.sended_sychronize IS '已发箱是否同步';
COMMENT ON COLUMN mail_account_replace.sending_sychronize IS '发件是否同步';
COMMENT ON COLUMN mail_account_replace.starttls_transport_secure IS 'STARTTLS是否加密传输';
COMMENT ON COLUMN mail_account_replace.account_default IS '默认发送邮箱';
COMMENT ON COLUMN mail_account_replace.status IS '邮箱账户状态 0 启用 1 禁用';
COMMENT ON TABLE mail_account_restraint_replace IS '邮件账户黑白名单表';
COMMENT ON COLUMN mail_account_restraint_replace.id IS '主键ID';
COMMENT ON COLUMN mail_account_restraint_replace.address IS '邮件账号';
COMMENT ON COLUMN mail_account_restraint_replace.employee_id IS '员工ID';
COMMENT ON COLUMN mail_account_restraint_replace.name IS '邮箱类型名';
COMMENT ON COLUMN mail_account_restraint_replace.account_type IS '邮箱类型 0：白名单 1：黑名单';
COMMENT ON COLUMN mail_account_restraint_replace.create_time IS '创建时间';
COMMENT ON COLUMN mail_account_restraint_replace.del_status IS '状态 0 正常 1删除';
COMMENT ON TABLE mail_tag_replace IS '标签表';
COMMENT ON COLUMN mail_tag_replace.id IS '主键ID';
COMMENT ON COLUMN mail_tag_replace.name IS '标签名';
COMMENT ON COLUMN mail_tag_replace.employee_id IS '员工关联ID';
COMMENT ON COLUMN mail_tag_replace.boarder IS '标签边框颜色';
COMMENT ON COLUMN mail_tag_replace.status IS '标签状态 0：启用 1：禁用';
COMMENT ON COLUMN mail_tag_replace.create_time IS '创建时间';
COMMENT ON COLUMN mail_tag_replace.del_status IS '是否删除 0 否 1 是';
COMMENT ON TABLE mail_signature_replace IS '邮件签名表';
COMMENT ON COLUMN mail_signature_replace.id IS '主键ID';
COMMENT ON COLUMN mail_signature_replace.title IS '签名标题';
COMMENT ON COLUMN mail_signature_replace.employee_id IS '员工关联ID';
COMMENT ON COLUMN mail_signature_replace.mail_account_id IS '标签关联邮箱账户';
COMMENT ON COLUMN mail_signature_replace.content IS '签名内容';
COMMENT ON COLUMN mail_signature_replace.signature_default IS '标签是否默认：0 默认 1 非默认';
COMMENT ON COLUMN mail_signature_replace.signature_type IS '标签类型：1:文本签名 2:名片签名';
COMMENT ON COLUMN mail_signature_replace.create_time IS '创建时间';
COMMENT ON COLUMN mail_signature_replace.del_status IS '删除状态 (0 正常 1删除)';
COMMENT ON COLUMN mail_signature_replace.status IS '启用状态 (0 启用 1 禁用)';
COMMENT ON TABLE mail_receive_condition_replace IS '邮件接收条件表';
COMMENT ON COLUMN mail_receive_condition_replace.id IS '主键ID';
COMMENT ON COLUMN mail_receive_condition_replace.name IS '标签标题';
COMMENT ON COLUMN mail_receive_condition_replace.employee_id IS '员工关联ID';
COMMENT ON COLUMN mail_receive_condition_replace.mail_account_id IS '标签关联邮箱账户';
COMMENT ON COLUMN mail_receive_condition_replace.status IS '收信规则状态：0 启用 1 禁用';
COMMENT ON COLUMN mail_receive_condition_replace.content IS '标签内容';
COMMENT ON COLUMN mail_receive_condition_replace.tag_default IS '标签是否默认：0 默认 1 非默认';
COMMENT ON COLUMN mail_receive_condition_replace.tag_type IS '标签类型：1:文本标签 2:名片标签';
COMMENT ON COLUMN mail_receive_condition_replace.create_time IS '创建时间';
COMMENT ON TABLE mail_catalog_replace IS '邮件通讯录表';
COMMENT ON COLUMN mail_catalog_replace.id IS '主键ID';
COMMENT ON COLUMN mail_catalog_replace.name IS '账户名称';
COMMENT ON COLUMN mail_catalog_replace.employee_id IS '员工关联ID';
COMMENT ON COLUMN mail_catalog_replace.mail_address IS '邮箱地址';
COMMENT ON COLUMN mail_catalog_replace.del_status IS '账户状态：0 启用 1 删除';
COMMENT ON COLUMN mail_catalog_replace.create_time IS '创建时间';
COMMENT ON TABLE mail_body_replace IS '邮件通讯录表';
COMMENT ON COLUMN mail_body_replace.id IS '主键ID';
COMMENT ON COLUMN mail_body_replace.subject IS '邮件主题';
COMMENT ON COLUMN mail_body_replace.from_recipient IS '发件人';
COMMENT ON COLUMN mail_body_replace.to_recipients IS '接收人';
COMMENT ON COLUMN mail_body_replace.cc_recipients IS '抄送人';
COMMENT ON COLUMN mail_body_replace.bcc_recipients IS '密送人';
COMMENT ON COLUMN mail_body_replace.mail_content IS '邮件内容';
COMMENT ON COLUMN mail_body_replace.embedded_images IS '嵌入图片';
COMMENT ON COLUMN mail_body_replace.cc_setting IS '抄送设置';
COMMENT ON COLUMN mail_body_replace.bcc_setting IS '密送设置';
COMMENT ON COLUMN mail_body_replace.single_show IS '群发单显设置';
COMMENT ON COLUMN mail_body_replace.is_emergent IS '0 否 1 是';
COMMENT ON COLUMN mail_body_replace.is_notification IS '0 否 1 是';
COMMENT ON COLUMN mail_body_replace.is_plain IS '0 否 1 是';
COMMENT ON COLUMN mail_body_replace.is_track IS '0 否 1 是';
COMMENT ON COLUMN mail_body_replace.is_encryption IS '0 否 1 是';
COMMENT ON COLUMN mail_body_replace.is_signature IS '0 否 1 是';
COMMENT ON TABLE mail_timer_replace IS '邮件定时发送表';
COMMENT ON COLUMN mail_timer_replace.id IS '主键ID';
COMMENT ON COLUMN mail_timer_replace.scope_id IS '定时所属';
COMMENT ON COLUMN mail_timer_replace.employee_id IS '员工id';
COMMENT ON COLUMN mail_timer_replace.timer_year IS '定时年';
COMMENT ON COLUMN mail_timer_replace.timer_month IS '定时月';
COMMENT ON COLUMN mail_timer_replace.timer_day IS '定时日';
COMMENT ON COLUMN mail_timer_replace.timer_hour IS '定时时';
COMMENT ON COLUMN mail_timer_replace.timer_minutes IS '定时分';
COMMENT ON COLUMN mail_timer_replace.timer_second IS '定时秒';
COMMENT ON COLUMN mail_timer_replace.create_time IS '创建时间';
COMMENT ON COLUMN mail_timer_replace.status IS '定时状态 0 未执行 1 已执行';
COMMENT ON TABLE mail_box_scope_replace IS '邮件所属分类';
COMMENT ON COLUMN mail_box_scope_replace.id IS '主键ID';
COMMENT ON COLUMN mail_box_scope_replace.mail_id IS '邮件id';
COMMENT ON COLUMN mail_box_scope_replace.mail_box_id IS '邮箱类型的ID';
COMMENT ON COLUMN mail_box_scope_replace.employee_id IS '员工id';
COMMENT ON COLUMN mail_box_scope_replace.create_time IS '创建时间';
COMMENT ON COLUMN mail_box_scope_replace.read_status IS '查看状态 0 未读 1 已读';
COMMENT ON COLUMN mail_box_scope_replace.timer_status IS '定时任务状态 0 未设定 1 设定';
COMMENT ON COLUMN mail_box_scope_replace.approval_status IS '审批状态 0 未通过 1 已通过';
COMMENT ON COLUMN mail_box_scope_replace.draft_status IS '草稿状态 0 不是 1 是';
COMMENT ON COLUMN mail_box_scope_replace.del_status IS '删除状态 0 未删除 1 已删除';
COMMENT ON TABLE mail_tag_scope_replace IS '邮件所属标签分类';
COMMENT ON COLUMN mail_tag_scope_replace.id IS '主键ID';
COMMENT ON COLUMN mail_tag_scope_replace.mail_id IS '邮件id';
COMMENT ON COLUMN mail_tag_scope_replace.tag_id IS '标签id';
COMMENT ON COLUMN mail_tag_scope_replace.employee_id IS '员工id';
COMMENT ON COLUMN mail_tag_scope_replace.create_time IS '创建时间';
COMMENT ON COLUMN mail_tag_scope_replace.read_status IS '查看状态 0 未读 1 已读';
COMMENT ON COLUMN mail_tag_scope_replace.timer_status IS '定时任务状态 0 未设定 1 设定';
COMMENT ON COLUMN mail_tag_scope_replace.approval_status IS '审批状态 0 未通过 1 已通过';
COMMENT ON TABLE mail_box_replace IS '邮箱的类型';
COMMENT ON COLUMN mail_box_replace.name IS '邮箱类型的名称';
COMMENT ON COLUMN mail_box_replace.status IS '邮箱类型的状态 0 有效 1 无效';
COMMENT ON TABLE mail_latest_account_replace IS '最近联系人表';
COMMENT ON COLUMN mail_latest_account_replace.id IS '主键ID';
COMMENT ON COLUMN mail_latest_account_replace.employee_id IS '发起人联系人的ID';
COMMENT ON COLUMN mail_latest_account_replace.contact_employee_id IS '联系人的ID';
COMMENT ON COLUMN mail_latest_account_replace.create_time IS '联系时间';
